version: '3.5'

services:
  app01: &app
    hostname: app01
    environment:
      - DB_PASSWORD=1234
      - DB_USER=admin
      - DB_NAME=rinha
      - DB_HOST=db
    depends_on:
      - db
    build: .
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: '0.12'
          memory: '150MB'

  app02:
    <<: *app
    ports:
      - "8082:8080"
    hostname: app02

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app01
      - app02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '10MB'

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -N 50 -c shared_buffers=256MB
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: "230MB"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  defalt:
    driver: bridge
    name: rinha-2024-q1